apiVersion: ethicalzen.ai/v1
kind: Environment
metadata:
  name: staging
  description: "Staging environment configuration for the Apex Capital asset management guardrail suite. All guardrails enabled in permissive mode for testing and calibration."
spec:
  tenants:
    - apex_capital
  guardrails:
    - unsuitable_advice_blocker
    - performance_guarantee_detector
    - market_manipulation_detector
    - insider_information_blocker
    - financial_pii_protector
    - unauthorized_trading_blocker
    - risk_disclosure_enforcer
    - fiduciary_duty_detector
    - aml_screening_guardrail
    - client_suitability_checker
  variables:
    validation_mode: permissive
    log_level: debug
    cache_enabled: "false"
    blockchain_record: "false"
    gateway_url: "https://gateway-staging.apex-capital.com"
    api_key_env: EZ_STAGING_API_KEY
    fail_open: "true"
    alert_channel: "#staging-alerts"
    audit_retention_days: "90"
